version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: tournament_bot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  bot:
    build: .
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/tournament_bot
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data:
